UASKelompok5/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\homeController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\KursusController;
use App\Http\Controllers\PendaftaranController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\InstrukturController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [homeController::class, 'index']);

Route::resource('siswa', SiswaController::class);
Route::resource('kursus', KursusController::class);
Route::resource('pendaftaran', PendaftaranController::class);
Route::resource('kelas', KelasController::class);
Route::resource('instruktur', InstrukturController::class);

Route::middleware(['auth'])->group(function () {
        Route::resource('kursus', KursusController::class);
        Route::resource('instruktur', InstrukturController::class);
        
});

Route::get('/master', function(){
    return view('layouts.master');
});

Auth::routes();

UASKelompok5/app/Models/Instruktur.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Instruktur extends Model
{
    use HasFactory;

    protected $table = 'instruktur';
    protected $fillable = [
        'nama',
        'email',
        'nomor_telepon',
        'keahlian'
    ];
}

UASKelompok5/app/Models/instruktur.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Instruktur extends Model
{
    use HasFactory;

    protected $table = 'instruktur';
    protected $fillable = [
        'nama',
        'email',
        'nomor_telepon',
        'keahlian'
    ];
}

UASKelompok5/app/Http/Controllers/InstrukturController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Instruktur;

class InstrukturController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $instrukturs = Instruktur::all();
        return view('instruktur.tampil', ['instrukturs' => $instrukturs]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('instruktur.tambah');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|string|max:255',
            'email' => 'required|email|max:255|unique:instruktur,email',
            'nomor_telepon' => 'required|string|max:15',
            'keahlian' => 'required|string|max:255',
        ]);

        Instruktur::create($request->all());
        return redirect()->route('instruktur.index');
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $instruktur = Instruktur::findOrFail($id);
        return view('instruktur.detail', ['instruktur' => $instruktur]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $instruktur = Instruktur::findOrFail($id);
        return view('instruktur.edit', ['instruktur' => $instruktur]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required|string|max:255',
            'email' => 'required|email|max:255|unique:instruktur,email,' . $id,
            'nomor_telepon' => 'required|string|max:15',
            'keahlian' => 'required|string|max:255',
        ]);

        $instruktur = Instruktur::findOrFail($id);
        $instruktur->update($request->all());
        return redirect()->route('instruktur.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        Instruktur::findOrFail($id)->delete();
        return redirect()->route('instruktur.index');
    }
}

UASKelompok5/resources/views/instruktur/detail.blade.php
@extends('layouts.master')

@section('content')
<h1>{{ $instruktur->nama }}</h1>
<p>Email: {{ $instruktur->email }}</p>
<p>No Telepon: {{ $instruktur->nomor_telepon }}</p>
<p>Keahlian: {{ $instruktur->keahlian }}</p>
@endsection

UASKelompok5/resources/views/instruktur/edit.blade.php
@extends('layouts.master')

@section('content')
<form method="POST" action="{{ route('instruktur.update', $instruktur->id) }}">
    @csrf
    @method('PUT')

    <div class="form-group">
      <label>Nama</label>
      <input type="text" class="form-control" name="nama" value="{{ $instruktur->nama }}">
    </div>
    <div class="form-group">
      <label>Email</label>
      <input type="email" class="form-control" name="email" value="{{ $instruktur->email }}">
    </div>
    <div class="form-group">
      <label>No Telepon</label>
      <input type="text" class="form-control" name="nomor_telepon" value="{{ $instruktur->nomor_telepon }}">
    </div>
    <div class="form-group">
      <label>Keahlian</label>
      <input type="text" class="form-control" name="keahlian" value="{{ $instruktur->keahlian }}">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

UASKelompok5/resources/views/instruktur/tambah.blade.php
@extends('layouts.master')

@section('content')
<form method="POST" action="{{ route('instruktur.store') }}">
    @csrf

    <div class="form-group">
      <label>Nama</label>
      <input type="text" class="form-control" name="nama">
    </div>
    <div class="form-group">
      <label>Email</label>
      <input type="email" class="form-control" name="email">
    </div>
    <div class="form-group">
      <label>No Telepon</label>
      <input type="text" class="form-control" name="nomor_telepon">
    </div>
    <div class="form-group">
      <label>Keahlian</label>
      <input type="text" class="form-control" name="keahlian">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

UASKelompok5/resources/views/instruktur/tampil.blade.php
@extends('layouts.master')

@section('content')
<a href="{{ route('instruktur.create') }}" class="btn btn-sm btn-primary">Tambah</a>

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Nama</th>
        <th scope="col">Email</th>
        <th scope="col">No Telepon</th>
        <th scope="col">Keahlian</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      @forelse ($instrukturs as $key => $instruktur)
      <tr>
        <th scope="row">{{ $key + 1 }}</th>
        <td>{{ $instruktur->nama }}</td>
        <td>{{ $instruktur->email }}</td>
        <td>{{ $instruktur->nomor_telepon }}</td>
        <td>{{ $instruktur->keahlian }}</td>
        <td>
            <form action="{{ route('instruktur.destroy', $instruktur->id) }}" method="POST">
                <a href="{{ route('instruktur.show', $instruktur->id) }}" class="btn btn-info btn-sm">Detail</a>
                <a href="{{ route('instruktur.edit', $instruktur->id) }}" class="btn btn-warning btn-sm">Edit</a>
                @csrf
                @method('DELETE')
                <input type="submit" value="Delete" class="btn btn-danger btn-sm">
            </form>
        </td>
      </tr>
      @empty
          <tr>
            <td colspan="6">Data Instruktur Belum Tersedia!</td>
          </tr>
      @endforelse
    </tbody>
  </table>
@endsection