UASKelompok5/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\homeController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\KursusController;
use App\Http\Controllers\PendaftaranController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\InstrukturController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [homeController::class, 'index']);

Route::resource('siswa', SiswaController::class);
Route::resource('kursus', KursusController::class);
Route::resource('pendaftaran', PendaftaranController::class);
Route::resource('kelas', KelasController::class);
Route::resource('instruktur', InstrukturController::class);

Route::middleware(['auth'])->group(function () {
        Route::resource('kursus', KursusController::class);
        Route::resource('instruktur', InstrukturController::class);
        
});

Route::get('/master', function(){
    return view('layouts.master');
});

Auth::routes();

UASKelompok5/app/Models/Pendaftaran.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Pendaftaran extends Model
{
    protected $table = 'pendaftaran';

    protected $fillable = ['tanggal_pendaftaran', 'status', 'siswa_idsiswa'];

    // Relasi dengan model Siswa
    public function siswa()
    {
        return $this->belongsTo('App\Models\Siswa', 'siswa_idsiswa');
    }
}

UASKelompok5/app/Http/Controllers/PendaftaranController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Pendaftaran;
use App\Models\Siswa; // Tambahkan model Siswa

class PendaftaranController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index','show']);
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $pendaftarans = Pendaftaran::all();
        return view('pendaftaran.tampil', ['pendaftarans' => $pendaftarans]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $siswas = Siswa::all(); // Ambil semua data siswa
        return view('pendaftaran.tambah', ['siswas' => $siswas]); // Kirim data siswa ke view
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'tanggal_pendaftaran' => 'required|date',
            'status' => 'required',
            'siswa_idsiswa' => 'required|exists:siswa,id', // Pastikan siswa_idsiswa ada di tabel siswa
        ]);

        Pendaftaran::create($request->all());
        return redirect()->route('pendaftaran.index'); // Mengarahkan ke rute index
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $pendaftaran = Pendaftaran::findOrFail($id);
        return view('pendaftaran.detail', ['pendaftaran' => $pendaftaran]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $pendaftaran = Pendaftaran::findOrFail($id);
        $siswas = Siswa::all(); // Ambil semua data siswa
        return view('pendaftaran.edit', ['pendaftaran' => $pendaftaran, 'siswas' => $siswas]); // Kirim data siswa ke view
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'tanggal_pendaftaran' => 'required|date',
            'status' => 'required',
            'siswa_idsiswa' => 'required|exists:siswa,id',
        ]);

        $pendaftaran = Pendaftaran::findOrFail($id);
        $pendaftaran->update($request->all());
        return redirect()->route('pendaftaran.index'); // Mengarahkan ke rute index
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        Pendaftaran::findOrFail($id)->delete();
        return redirect()->route('pendaftaran.index'); // Mengarahkan ke rute index
    }
}

UASKelompok5/resources/views/pendaftaran/detail.blade.php
@extends('layouts.master')

@section('content')
<h1>{{ $pendaftaran->siswa->username }}</h1>
<p>Tanggal Pendaftaran: {{ $pendaftaran->tanggal_pendaftaran }}</p>
<p>Status: {{ $pendaftaran->status }}</p>
@endsection

UASKelompok5/resources/views/pendaftaran/edit.blade.php
@extends('layouts.master')

@section('content')
<form method="POST" action="{{ route('pendaftaran.update', $pendaftaran->id) }}">
    @csrf
    @method('PUT')

    {{-- Validation Errors --}}
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="form-group">
        <label for="tanggal_pendaftaran">Tanggal Pendaftaran</label>
        <input type="date" class="form-control" name="tanggal_pendaftaran" id="tanggal_pendaftaran" value="{{ $pendaftaran->tanggal_pendaftaran }}">
    </div>

    <div class="form-group">
        <label for="status">Status</label>
        <select name="status" id="status" class="form-control">
            <option value="Aktif" {{ $pendaftaran->status == 'Aktif' ? 'selected' : '' }}>Aktif</option>
            <option value="Tidak Aktif" {{ $pendaftaran->status == 'Tidak Aktif' ? 'selected' : '' }}>Tidak Aktif</option>
        </select>
    </div>

    <div class="form-group">
        <label for="siswa_idsiswa">Siswa</label>
        <select name="siswa_idsiswa" id="siswa_idsiswa" class="form-control">
            @foreach($siswas as $siswa)
                <option value="{{ $siswa->id }}" {{ $pendaftaran->siswa_idsiswa == $siswa->id ? 'selected' : '' }}>{{ $siswa->name }}</option>
            @endforeach
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

UASKelompok5/resources/views/pendaftaran/tambah.blade.php
@extends('layouts.master')

@section('content')
<form method="POST" action="{{ route('pendaftaran.store') }}">
    @csrf

    {{-- Validation Errors --}}
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="form-group">
        <label for="tanggal_pendaftaran">Tanggal Pendaftaran</label>
        <input type="date" class="form-control" name="tanggal_pendaftaran" id="tanggal_pendaftaran">
    </div>

    <div class="form-group">
        <label for="status">Status</label>
        <select name="status" id="status" class="form-control">
            <option value="Aktif">Aktif</option>
            <option value="Tidak Aktif">Tidak Aktif</option>
        </select>
    </div>

    <div class="form-group">
        <label for="siswa_idsiswa">Siswa</label>
        <select name="siswa_idsiswa" id="siswa_idsiswa" class="form-control">
            @foreach($siswas as $siswa)
                <option value="{{ $siswa->id }}">{{ $siswa->name }}</option>
            @endforeach
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

UASKelompok5/resources/views/pendaftaran/tampil.blade.php
@extends('layouts.master')

@section('content')
@auth
<a href="{{ route('pendaftaran.create') }}" class="btn btn-sm btn-primary">Tambah</a>
@endauth


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Nama Siswa</th>
            <th scope="col">Tanggal Pendaftaran</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($pendaftarans as $key => $pendaftaran)
        <tr>
            <th scope="row">{{ $key + 1 }}</th>
            <td>{{ $pendaftaran->siswa->name }}</td>
            <td>{{ $pendaftaran->tanggal_pendaftaran }}</td>
            <td>{{ $pendaftaran->status }}</td>
            <td>
                <form action="{{ route('pendaftaran.destroy', $pendaftaran->id) }}" method="POST">
                    <a href="{{ route('pendaftaran.show', $pendaftaran->id) }}" class="btn btn-info btn-sm">Detail</a>
                    @auth
                    <a href="{{ route('pendaftaran.edit', $pendaftaran->id) }}" class="btn btn-warning btn-sm">Edit</a>
                    @csrf
                    @method('DELETE')
                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                    @endauth
                </form>
            </td>
        </tr>
        @empty
        <tr>
            <td colspan="5">Tidak ada data pendaftaran</td>
        </tr>
        @endforelse
    </tbody>
</table>
@endsection