UASKelompok5/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\homeController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\KursusController;
use App\Http\Controllers\PendaftaranController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\InstrukturController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [homeController::class, 'index']);

Route::resource('siswa', SiswaController::class);
Route::resource('kursus', KursusController::class);
Route::resource('pendaftaran', PendaftaranController::class);
Route::resource('kelas', KelasController::class);
Route::resource('instruktur', InstrukturController::class);

Route::middleware(['auth'])->group(function () {
        Route::resource('kursus', KursusController::class);
        Route::resource('instruktur', InstrukturController::class);
        
});

Route::get('/master', function(){
    return view('layouts.master');
});

Auth::routes();

UASKelompok5/app/Models/Kelas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    use HasFactory;

    protected $table = 'kelas';
    protected $fillable = [
        'tanggal_mulai',
        'tanggal_selesai',
        'kapasitas',
        'pendaftaran_idpendaftaran',
        'instruktur_idinstruktur',
        'kursus_idkursus',
    ];

    public function pendaftaran()
    {
        return $this->belongsTo(Pendaftaran::class, 'pendaftaran_idpendaftaran');
    }

    public function instruktur()
    {
        return $this->belongsTo(Instruktur::class, 'instruktur_idinstruktur');
    }

    public function kursus()
    {
        return $this->belongsTo(Kursus::class, 'kursus_idkursus');
    }
}

UASKelompok5/app/Models/kelas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    use HasFactory;

    protected $table = 'kelas';
    protected $fillable = [
        'tanggal_mulai',
        'tanggal_selesai',
        'kapasitas',
        'pendaftaran_idpendaftaran',
        'instruktur_idinstruktur',
        'kursus_idkursus',
    ];

    public function pendaftaran()
    {
        return $this->belongsTo(Pendaftaran::class, 'pendaftaran_idpendaftaran');
    }

    public function instruktur()
    {
        return $this->belongsTo(Instruktur::class, 'instruktur_idinstruktur');
    }

    public function kursus()
    {
        return $this->belongsTo(Kursus::class, 'kursus_idkursus');
    }
}

UASKelompok5/app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kelas;
use App\Models\Pendaftaran;
use App\Models\Instruktur;
use App\Models\Kursus;

class KelasController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index','show']);
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $kelases = Kelas::with('pendaftaran.siswa', 'instruktur', 'kursus')->get();
        return view('kelas.tampil', ['kelases' => $kelases]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $pendaftarans = Pendaftaran::where('status', 'Aktif')->with('siswa')->get();
        $instrukturs = Instruktur::all();
        $kursuses = Kursus::all();

        return view('kelas.tambah', [
            'pendaftarans' => $pendaftarans,
            'instrukturs' => $instrukturs,
            'kursuses' => $kursuses,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'tanggal_mulai' => 'required|date',
            'tanggal_selesai' => 'required|date|after:tanggal_mulai',
            'kapasitas' => 'required|integer|min:1',
            'pendaftaran_idpendaftaran' => 'required|exists:pendaftaran,id',
            'instruktur_idinstruktur' => 'required|exists:instruktur,id',
            'kursus_idkursus' => 'required|exists:kursus,id',
        ]);

        Kelas::create($request->all());
        return redirect()->route('kelas.index');
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $kelas = Kelas::with('pendaftaran.siswa', 'instruktur', 'kursus')->findOrFail($id);
        return view('kelas.detail', ['kelas' => $kelas]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $kelas = Kelas::with('pendaftaran.siswa', 'instruktur', 'kursus')->findOrFail($id);
        $pendaftarans = Pendaftaran::where('status', 'Aktif')->with('siswa')->get();
        $instrukturs = Instruktur::all();
        $kursuses = Kursus::all();

        return view('kelas.edit', [
            'kelas' => $kelas,
            'pendaftarans' => $pendaftarans,
            'instrukturs' => $instrukturs,
            'kursuses' => $kursuses,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'tanggal_mulai' => 'required|date',
            'tanggal_selesai' => 'required|date|after:tanggal_mulai',
            'kapasitas' => 'required|integer|min:1',
            'pendaftaran_idpendaftaran' => 'required|exists:pendaftaran,id',
            'instruktur_idinstruktur' => 'required|exists:instruktur,id',
            'kursus_idkursus' => 'required|exists:kursus,id',
        ]);

        $kelas = Kelas::findOrFail($id);
        $kelas->update($request->all());
        return redirect()->route('kelas.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        Kelas::findOrFail($id)->delete();
        return redirect()->route('kelas.index');
    }
}

UASKelompok5/resources/views/kelas/detail.blade.php
@extends('layouts.master')

@section('content')
<h1>Detail Kelas</h1>
<p>Tanggal Mulai: {{ $kelas->tanggal_mulai }}</p>
<p>Tanggal Selesai: {{ $kelas->tanggal_selesai }}</p>
<p>Kapasitas: {{ $kelas->kapasitas }}</p>
<p>Siswa: {{ $kelas->pendaftaran->siswa->name }}</p>
<p>Instruktur: {{ $kelas->instruktur->nama }}</p>
<p>Kursus: {{ $kelas->kursus->materi }}</p>
@endsection

UASKelompok5/resources/views/kelas/edit.blade.php
@extends('layouts.master')

@section('content')
<form method="POST" action="{{ route('kelas.update', $kelas->id) }}">
    @csrf
    @method('PUT')

    <div class="form-group">
      <label>Tanggal Mulai</label>
      <input type="date" class="form-control" name="tanggal_mulai" value="{{ $kelas->tanggal_mulai }}">
    </div>
    <div class="form-group">
      <label>Tanggal Selesai</label>
      <input type="date" class="form-control" name="tanggal_selesai" value="{{ $kelas->tanggal_selesai }}">
    </div>
    <div class="form-group">
      <label>Kapasitas</label>
      <input type="number" class="form-control" name="kapasitas" value="{{ $kelas->kapasitas }}">
    </div>
    <div class="form-group">
      <label>Siswa</label>
      <select class="form-control" name="pendaftaran_idpendaftaran">
          @foreach($pendaftarans as $pendaftaran)
              <option value="{{ $pendaftaran->id }}" {{ $kelas->pendaftaran_idpendaftaran == $pendaftaran->id ? 'selected' : '' }}>{{ $pendaftaran->siswa->name }}</option>
          @endforeach
      </select>
    </div>
    <div class="form-group">
      <label>Instruktur</label>
      <select class="form-control" name="instruktur_idinstruktur">
          @foreach($instrukturs as $instruktur)
              <option value="{{ $instruktur->id }}" {{ $kelas->instruktur_idinstruktur == $instruktur->id ? 'selected' : '' }}>{{ $instruktur->nama }}</option>
          @endforeach
      </select>
    </div>
    <div class="form-group">
      <label>Kursus</label>
      <select class="form-control" name="kursus_idkursus">
          @foreach($kursuses as $kursus)
              <option value="{{ $kursus->id }}" {{ $kelas->kursus_idkursus == $kursus->id ? 'selected' : '' }}>{{ $kursus->materi }}</option>
          @endforeach
      </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

UASKelompok5/resources/views/kelas/tambah.blade.php
@extends('layouts.master')

@section('content')
<form method="POST" action="{{ route('kelas.store') }}">
    @csrf

    <div class="form-group">
      <label>Tanggal Mulai</label>
      <input type="date" class="form-control" name="tanggal_mulai">
    </div>
    <div class="form-group">
      <label>Tanggal Selesai</label>
      <input type="date" class="form-control" name="tanggal_selesai">
    </div>
    <div class="form-group">
      <label>Kapasitas</label>
      <input type="number" class="form-control" name="kapasitas">
    </div>
    <div class="form-group">
      <label>Siswa</label>
      <select class="form-control" name="pendaftaran_idpendaftaran">
          @foreach($pendaftarans as $pendaftaran)
              <option value="{{ $pendaftaran->id }}">{{ $pendaftaran->siswa->name }}</option>
          @endforeach
      </select>
    </div>
    <div class="form-group">
      <label>Instruktur</label>
      <select class="form-control" name="instruktur_idinstruktur">
          @foreach($instrukturs as $instruktur)
              <option value="{{ $instruktur->id }}">{{ $instruktur->nama }}</option>
          @endforeach
      </select>
    </div>
    <div class="form-group">
      <label>Kursus</label>
      <select class="form-control" name="kursus_idkursus">
          @foreach($kursuses as $kursus)
              <option value="{{ $kursus->id }}">{{ $kursus->materi }}</option>
          @endforeach
      </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

UASKelompok5/resources/views/kelas/tampil.blade.php
@extends('layouts.master')

@section('content')
@auth
<a href="{{ route('kelas.create') }}" class="btn btn-sm btn-primary">Tambah</a>
@endauth


<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Tanggal Mulai</th>
        <th scope="col">Tanggal Selesai</th>
        <th scope="col">Kapasitas</th>
        <th scope="col">Siswa</th>
        <th scope="col">Instruktur</th>
        <th scope="col">Kursus</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      @forelse ($kelases as $key => $kelas)
      <tr>
        <th scope="row">{{ $key + 1 }}</th>
        <td>{{ $kelas->tanggal_mulai }}</td>
        <td>{{ $kelas->tanggal_selesai }}</td>
        <td>{{ $kelas->kapasitas }}</td>
        <td>{{ $kelas->pendaftaran->siswa->name }}</td>
        <td>{{ $kelas->instruktur->nama }}</td>
        <td>{{ $kelas->kursus->materi }}</td>
        <td>
          <form action="{{ route('kelas.destroy', $kelas->id) }}" method="POST">
            <a href="{{ route('kelas.show', $kelas->id) }}" class="btn btn-info btn-sm">Detail</a>
          @auth
            <a href="{{ route('kelas.edit', $kelas->id) }}" class="btn btn-warning btn-sm">Edit</a>
            @csrf
            @method('DELETE')
            <input type="submit" value="Delete" class="btn btn-danger btn-sm">
        </form>
          @endauth
        </td>
      </tr>
      @empty
          <tr>
            <td colspan="8">Data Kelas Belum Tersedia!</td>
          </tr>
      @endforelse
    </tbody>
  </table>
@endsection